defaults: &defaults
  adapter: mysql
  username: root
  password: root

development:
  <<: *defaults
  database: invitator_development

test: &test
  <<: *defaults
  database: invitator_test

production:
  <<: *defaults
  database: invitator_production
